language: android
jdk:
  - oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-28.0.3
    - android-28

    # Support library
    - extra-android-support
    - extra-android-m2repository
script:
  - ./gradlew assembleMyBuild --stacktrace
