language: android
jdk:
  - oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - tools
    - platform-tools
    - tools

    - build-tools-28.0.3
    - android-28

    # Support library
    - extra-android-support
    - extra-android-m2repository
before_install:
  - pwd
  - ls -la
  - chmod +x ./gradlew
